import tkinter as tk
from tkinter import messagebox
root = tk.Tk()
root.name("Rejestracja na festiwal")
# Etykiety i pola tekstowe

label_name = tk.Label(root, text="Imię:")
label_name.grid(row=0, column=0, padx=10, pady=5, sticky="w")
entry_name = tk.Entry(root, width=40)
entry_name.grid(row=0, column=1, padx=10, pady=5)
label_lastname = tk.Label(root, text="Nazwisko:")
label_lastname.grid(row=1, column=0, padx=10, pady=5, sticky="w")
entry_lastname = tk.Entry(root, width=40)
entry_lastname.grid(row=1, column=1, padx=10, pady=5)
label_email = tk.Label(root, text="Adres email:")
label_email.grid(row=2, column=0, padx=10, pady=5, sticky="w")
entry_email = tk.Entry(root, width=40)
entry_email.grid(row=2, column=1, padx=10, pady=5)
label_phone = tk.Label(root, text="Numer telefonu:")
label_phone.grid(row=3, column=0, padx=10, pady=5, sticky="w")
entry_phone = tk.Entry(root, width=40)
entry_phone.grid(row=3, column=1, padx=10, pady=5)
label_city = tk.Label(root, text="Miasto:")
label_city.grid(row=4, column=0, padx=10, pady=5, sticky="w")
entry_city= tk.Entry(root, width=40)
entry_city.grid(row=4, column=1, padx=10, pady=5)
label_country = tk.Label(root, text="Kraj:")
label_country.grid(row=5, column=0, padx=10, pady=5, sticky="w")
entry_country = tk.Entry(root, width=40)
entry_country.grid(row=5, column=1, padx=10, pady=5)
label_birthdate = tk.Label(root, text="Data urodzenia:")
label_birthdate.grid(row=6, column=0, padx=10, pady=5, sticky="w")
entry_birthdate = tk.Entry(root, width=40)
entry_birthdate.grid(row=6, column=1, padx=10, pady=5)
label_pesel= tk.Label(root, text="Pesel:")
label_pesel.grid(row=7, column=0, padx=10, pady=5, sticky="w")
entry_pesel = tk.Entry(root, width=40)
entry_pesel.grid(row=7, column=1, padx=10, pady=5)
label_degree = tk.Label(root, text="Wykształcenie:")
label_degree.grid(row=8, column=0, padx=10, pady=5, sticky="w")
entry_degree = tk.Entry(root, width=40)
entry_degree.grid(row=8, column=1, padx=10, pady=5)
label_exp = tk.Label(root, text="Doświadczenie wolontariackie:")
label_exp.grid(row=9, column=0, padx=10, pady=5, sticky="w")
entry_exp = tk.Entry(root, width=40)
entry_exp.grid(row=9, column=1, padx=10, pady=5)
label_language = tk.Label(root, text="Języki obce:")
label_language.grid(row=10, column=0, padx=10, pady=5, sticky="w")
entry_language = tk.Entry(root, width=40)
entry_language.grid(row=10, column=1, padx=10, pady=5)
label_preferances = tk.Label(root, text="Preferencje wolontariackie:")
label_preferances.grid(row=11, column=0, padx=10, pady=5, sticky="w")
entry_preferances = tk.Entry(root, width=40)
entry_preferances.grid(row=11, column=1, padx=10, pady=5)
label_license = tk.Label(root, text="Czy posiadasz prawo jazdy?:")
label_license.grid(row=12, column=0, padx=10, pady=5, sticky="w")
entry_license = tk.Entry(root, width=40)
entry_license.grid(row=12, column=1, padx=10, pady=5)
label_time = tk.Label(root, text="Dostępność czasowa (ilość godzin w tygodniu):")
label_time.grid(row=13, column=0, padx=10, pady=5, sticky="w")
entry_time = tk.Entry(root, width=40)
entry_time.grid(row=13, column=1, padx=10, pady=5)
label_accommodation = tk.Label(root, text="Czy potrzebujesz zakwaterowania?:")
label_accommodation.grid(row=14, column=0, padx=10, pady=5, sticky="w")
entry_accommodation = tk.Entry(root, width=40)
entry_accommodation.grid(row=14, column=1, padx=10, pady=5)
label_size = tk.Label(root, text="Rozmiar koszulki:")
label_size.grid(row=15, column=0, padx=10, pady=5, sticky="w")
entry_size = tk.Entry(root, width=40)
entry_size.grid(row=15, column=1, padx=10, pady=5)
label_references = tk.Label(root, text="Referencje:")
label_references.grid(row=16, column=0, padx=10, pady=5, sticky="w")
entry_references = tk.Entry(root, width=40)
entry_references.grid(row=16, column=1, padx=10, pady=5)
label_reason = tk.Label(root, text="Dlaczego chcesz być wolontariuszem?:")
label_reason.grid(row=17, column=0, padx=10, pady=5, sticky="w")
entry_reason = tk.Entry(root, width=40)
entry_reason.grid(row=17, column=1, padx=10, pady=5)
label_additional = tk.Label(root, text="Uwagi dodatkowe:")
label_additional.grid(row=18, column=0, padx=10, pady=5, sticky="w")
entry_additional = tk.Entry(root, width=40)
entry_additional.grid(row=18, column=1, padx=10, pady=5)
label_info = tk.Label(root, text="Skąd dowiedzialeś/aś się o wydarzeniu?:")
label_info.grid(row=19, column=0, padx=10, pady=5, sticky="w")
entry_info = tk.Entry(root, width=40)
entry_info.grid(row=19, column=1, padx=10, pady=5)

# Przycisk zapisu
button_save = tk.Button(root, text="Zapisz", command=lambda x:x)
button_save.grid(row=20, column=0, columnspan=2, pady=10)
# Uruchomienie pętli głównej
root.mainloop()